### ISSUE TITLE
Cant require lib as per the documentation

### ISSUE THREAD

**Issue by dogmatic69** [Nixinova/Linguist#1]
```
const linguist = require('linguist-js');
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /app/node_modules/linguist-js/index.js from /app/code.js not supported.
Instead change the require of index.js in /app/code.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/app/code.js:1:18)
    at Object.<anonymous> (/app/index.js:2:14) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
```

**Comment by dogmatic69** [comment]
upgraded and the issue went away :)

**Comment by Nixinova** [comment]
> upgraded and the issue went away :)

Yep, versions 1.0.0–1.2.3 are all ESModules.
